Tripoint Hostility tweaks + Retake The Falklands v1
dcs-retribution/dcs-retribution pull request #216
Opened 2023-11-05 19:06 UTC by tmz42

Modified Tripoint 
- 'From Turkey' flights actually start from Incirlik
- Added F-15E in Incirlik
- Added Carrier group

Added v1 of Retake The Falklands based on Fuzzle's Gran Polvorin
- Campaign files
- Factions UK + US Falklands task force / Argentina+China occupation force

2023-11-05 20:05 UTC, Raffson requested changes
Aside from the comment, if possible, rebase your branch on dev?

2023-11-05 20:05 UTC, Raffson commented on resources/campaigns/tripoint_hostility.yaml
> +version: "11.0"
I believe we're still at 10.7 😅

2023-11-06 10:15 UTC, tmz42 commented
OK, I think the changes are done, hope I didn't screw anything up... can you check if this seems OK to you?

2023-11-06 18:48 UTC, Raffson approved these changes

2023-11-06 18:48 UTC, merged