Update usa_2005.json
dcs-retribution/dcs-retribution pull request #367
Opened 2024-07-16 12:46 UTC by ColonelAkirNakesh

Adjust spacing in some flyable aircraft (tabs vs spaces), 
Adds MRAP and new Abrams model
Removes Hornet livery enforcement

2024-07-16 20:32 UTC, Raffson requested changes

2024-07-16 20:32 UTC, Raffson commented on resources/factions/usa_2005.json
> -}
Why did you remove the livery overrides exactly? 😅

2024-07-16 20:55 UTC, ColonelAkirNakesh commented
I thought it was redundant with the squadron system and they weren't
necessary since we have US Hornet squadrons?

Is it possible to revert those changes and still add the Abrams and MRAP or
should I delete this one and start a new pull request?

On Tue, Jul 16, 2024 at 1:33 PM Raffson ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In resources/factions/usa_2005.json
> <https://github.com/dcs-retribution/dcs-retribution/pull/367#discussion_r1680032373>
> :
>
> > -  "jtac_unit": "MQ-9 Reaper",
> -  "liveries_overrides": {
> -    "F/A-18C Hornet (Lot 20)": [
> -      "VFA-106",
> -      "VFA-113",
> -      "VFA-122",
> -      "VFA-131",
> -      "VFA-192",
> -      "VFA-34",
> -      "VFA-37",
> -      "VFA-83",
> -      "VFA-87",
> -      "VFA-97",
> -      "VMFA-122",
> -      "VMFA-132",
> -      "VMFA-251",
> -      "VMFA-312",
> -      "VMFA-314",
> -      "VMFA-323"
> -    ]
> -  }
> -}
>
> Why did you remove the livery overrides exactly? 😅
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dcs-retribution/dcs-retribution/pull/367#pullrequestreview-2181255463>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWKLLS6ZEQNLA7GHIVXXHULZMV7QLAVCNFSM6AAAAABK6QU5LGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOBRGI2TKNBWGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-17 05:41 UTC, Raffson commented
Livery-overrides are still used, but as a fallback in case no livery or livery-set was defined for a specific squadron, so it's still applicable.

You can indeed revert the change on this branch, no need for a new PR 😉

2024-07-17 22:11 UTC, ColonelAkirNakesh commented
OK... I edited and hopefully I was able to restore the liveries! Sorry for
being such a noob.

On Tue, Jul 16, 2024 at 10:42 PM Raffson ***@***.***> wrote:

> Livery-overrides are still used, but as a fallback in case no livery or
> livery-set was defined for a specific squadron, so it's still applicable.
>
> You can indeed revert the change on this branch, no need for a new PR 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dcs-retribution/dcs-retribution/pull/367#issuecomment-2232461793>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWKLLSZ3YOIBOUJJ3VKCYSTZMX73VAVCNFSM6AAAAABK6QU5LGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMZSGQ3DCNZZGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-18 10:25 UTC, Raffson commented
No worries, you're actually doing pretty good 😉

2024-07-18 10:25 UTC, Raffson approved these changes

2024-07-18 10:37 UTC, merged