Various Iran 2015 updates: adds F-5 FC2024 flyable, consistent Iran liveries across planeset
dcs-retribution/dcs-retribution pull request #369
Opened 2024-07-16 19:40 UTC by ColonelAkirNakesh

Changes F1EQ to EE to make it flyable.
Add F-5 FC2024
Removed aircraft that don't have Iran liveries as part of core game (Hind, Su-25T) Change IL-76  to C-130 (which has Iran livery in core game) Change Reaper to Wingloong
Enforce Iran liveries for modules with possibility for non-Iran liveries appearing -- F-4E, F-5, MiG-21 and Mirage F1

2024-07-16 20:30 UTC, Raffson requested changes
I see many aircraft got removed, but why? 😅

2024-07-16 20:30 UTC, Raffson commented on resources/factions/iran_2015.json
> +    "Mirage-F1EE",
Don't swap this one out, rather add it next to the EQ 😉

2024-07-16 20:30 UTC, Raffson commented on resources/factions/iran_2015.json
> -    "Su-22M4 Fitter-K",
Why did the fitter get removed exactly? 😅

2024-07-16 20:56 UTC, ColonelAkirNakesh commented
Ah I thought it would be good to clean out the generic airplane liveries
that don't have the Iran liveries, but if that was too aggressive is it
possible to just revert the changes, add the livery enforcement and FC3 F-5
and add the Mirage F1EE as you mentioned or should I start a new request?
Thanks and sorry for being a noob haha

On Tue, Jul 16, 2024 at 1:30 PM Raffson ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I see many aircraft got removed, but why? 😅
> ------------------------------
>
> In resources/factions/iran_2015.json
> <https://github.com/dcs-retribution/dcs-retribution/pull/369#discussion_r1680027866>
> :
>
> >      "MiG-21bis Fishbed-N",
>      "MiG-29A Fulcrum-A",
> -    "Mirage-F1EQ",
> -    "Su-22M4 Fitter-K",
> +    "Mirage-F1EE",
>
> Don't swap this one out, rather add it next to the EQ 😉
> ------------------------------
>
> In resources/factions/iran_2015.json
> <https://github.com/dcs-retribution/dcs-retribution/pull/369#discussion_r1680028490>
> :
>
> >      "MiG-21bis Fishbed-N",
>      "MiG-29A Fulcrum-A",
> -    "Mirage-F1EQ",
> -    "Su-22M4 Fitter-K",
>
> Why did the fitter get removed exactly? 😅
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dcs-retribution/dcs-retribution/pull/369#pullrequestreview-2181247946>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWKLLSYXUWXGGO4GMMXKC3DZMV7GTAVCNFSM6AAAAABK7HNN4CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOBRGI2DOOJUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-17 05:44 UTC, Raffson commented
No worries, you can still revert the deleted aircraft in the same PR 😉

2024-07-18 13:01 UTC, closed without merging

2024-07-18 13:02 UTC, ColonelAkirNakesh commented
I think I'll kill this one off and try to make actual squadrons instead of
livery overrides for the Iranian modules that don't have em :)

On Tue, Jul 16, 2024 at 10:44 PM Raffson ***@***.***> wrote:

> No worries, you can still revert the deleted aircraft in the same PR 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dcs-retribution/dcs-retribution/pull/369#issuecomment-2232463961>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWKLLSY5STRPUPSBXQWM7HLZMYAEXAVCNFSM6AAAAABK7HNN4CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMZSGQ3DGOJWGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>