Add ability to select loadout on flight creation
dcs-retribution/dcs-retribution pull request #426
Opened 2024-12-12 01:12 UTC by Druss99

These changes allow for users to select a loadout for a flight during flight creation. Tested in retribution UI and checked the created mission to ensure loadouts were properly adjusted.

2024-12-12 01:19 UTC, Druss99 commented
This could probably use a few added features like showing the payload when you hover over the name of the loadout or perhaps the full payload preview like on the payload editor page. Dropping this PR in to get an idea of what we might want to fledge out to consider it a full feature or if this is a good start that can be merged in and iterated on in the future.

2024-12-12 03:50 UTC, Druss99 commented
Added showing the payload when you hover over a loadout and set the default loadout in the drop down based on task selected

2024-12-12 18:39 UTC, Raffson requested changes

2024-12-12 18:39 UTC, Raffson commented on qt_ui/windows/mission/flight/QFlightCreator.py
> +                break
This part could be refactored, along with the same piece from `on_aircraft_changed`, say to a method called `_init_loadout_selector`?

2024-12-12 18:39 UTC, Raffson commented on qt_ui/windows/mission/flight/QFlightCreator.py
> +                    break
For reference, this is the common part afaict 😅

2024-12-13 02:44 UTC, Druss99 commented
Changed the loadout selector init to a method, tested and all looks good, let me know if I missed anything!

2024-12-14 22:38 UTC, Raffson approved these changes

2024-12-14 22:38 UTC, merged