Default settings support
dcs-retribution/dcs-retribution pull request #428
Opened 2024-12-15 23:11 UTC by Druss99

This PR allows users to overwrite the Default.zip file (now created automatically on new campaign creation) with their preferred user settings for campaigns.

2024-12-16 12:28 UTC, Raffson requested changes

2024-12-16 12:28 UTC, Raffson commented on qt_ui/windows/newgame/WizardPages/QNewGameSettings.py
> +            "\nAll other options unrelated to campaign generation. Defaults can be changed by overwriting Defualt.zip"
Small typo in `Defualt.zip` 😅

2024-12-16 12:36 UTC, Druss99 commented on qt_ui/windows/newgame/WizardPages/QNewGameSettings.py
> +            "\nAll other options unrelated to campaign generation. Defaults can be changed by overwriting Defualt.zip"
fixed lol

2024-12-18 12:46 UTC, Raffson approved these changes

2024-12-18 12:47 UTC, merged